services:
  server:
    build: ./server
    container_name: server_container
    restart: always
    ports:
      - "5000:5000"
    env_file:
      - ./server/.env.docker
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: client_container
    restart: always
    ports:
      - "5173:5173"
    env_file:
      - ./client/.env.docker
    depends_on:
      - server

  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    container_name: mongodb_container
    restart: always
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=quangtan
      - MONGO_INITDB_ROOT_PASSWORD=quangtan
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: